### ISSUE TITLE
Tact v1.3.0 release checklist

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact#280]
- [x] Improve the changelog for v1.3.0: grammar, wording, polishing (PR #281)
- [x] Make sure there are no open issues for the [v1.3.0 milestone](https://github.com/tact-lang/tact/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.3.0) (except for the current one, of course)
- [x] Bump Tact version (PR #321)
- [x] Tag a new release in git
- [x] Create the new release on GitHub: https://github.com/tact-lang/tact/releases
- [x] Update [tact-docs](https://github.com/tact-lang/tact-docs) with the most recent Tact features: https://github.com/tact-lang/tact-docs/milestone/2
- [x] Publish the package on NPM
- [x] Request or perform the plugins/parsers/tools updates:
   - [x] https://github.com/tact-lang/tact-vscode (tracked in: https://github.com/tact-lang/tact-vscode/issues/32) (+ a new release on the marketplace)
   - [x] https://github.com/tact-lang/tact.vim
   - [x] https://github.com/tact-lang/tree-sitter-tact
   - [ ] https://github.com/ton-blockchain/intellij-ton (tracked in: https://github.com/ton-blockchain/intellij-ton/issues/177)
   - [x] https://github.com/tact-lang/tact-template (PR: https://github.com/tact-lang/tact-template/pull/18)
   - [x] https://github.com/ton-org/blueprint (tracked in: https://github.com/ton-org/blueprint/pull/96)
   - [x] https://github.com/nujan-io/nujan-ide (tracked in: https://github.com/nujan-io/nujan-ide/issues/33)
   - [x] Prism.js: https://github.com/novusnota/prism-ton/issues/2 and https://github.com/TelegramMessenger/libprisma/pull/13/commits/caa589d6004a0dad77543abdd858664007aab5c3 (Telegram syntax highlighting PR by @novusnota)
- ~~[ ] [TON Dev News](https://t.me/tondev_news) Telegram channel announcement~~ (postponed to v1.3.1)
- ~~[ ] Accumulate TON dev chats feedback~~ (postponed to v1.3.1)

**Comment by novusnota** [comment]
Added Nujan to that update list

**Comment by novusnota** [comment]
Updated [tact.vim](https://github.com/tact-lang/tact.vim) and [tree-sitter-tact](https://github.com/tact-lang/tree-sitter-tact) to match Tact 1.3.0, except for the upcoming map traversing functionality #106

UPD: fully updated both to Tact 1.3.0

**Comment by 0kenx** [comment]
Any expected timeline for the 1.3.0 release?

**Comment by anton-trunov** [comment]
@0kenx published on NPM: https://www.npmjs.com/package/@tact-lang/compiler/v/1.3.0

**Comment by 0kenx** [comment]
❤️❤️❤️❤️

**Comment by anton-trunov** [comment]
https://github.com/tact-lang/tact/issues/375 supersedes this now
