### ISSUE TITLE
Tact v1.3.1 release checklist

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact#375]
- [x] Improve the changelog for `v1.3.1`: grammar, wording, polishing (PR #387)
- [x] Make sure there are no open issues for the [v1.3.1 milestone](https://github.com/tact-lang/tact/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.3.1)
      (except for the current one, of course)
- [x] Bump Tact version in (PR #387):
  - [x] [`package.json`](./package.json) file
  - [x] [CHANGELOG.md](./CHANGELOG.md): `Unreleased` -> `v1.3.1`
- [x] Tag the new `v1.3.1` release in Git
  ```shell
  $ git tag -a v1.3.1
  $ git push origin v1.3.1
  ```
- [x] Create the new `v1.3.1` release on GitHub: <https://github.com/tact-lang/tact/releases>
- [x] Publish the new `v1.3.1` release on NPM:
      [@tact-lang/compiler](https://www.npmjs.com/package/@tact-lang/compiler)
  ```shell
  $ git checkout v1.3.1
  $ yarn all && npm publish
  ```
- [x] Write `v1.3` release notes explaining the newest changes with code examples ~~and commit those to this repository~~
- [x] [TON Dev News](https://t.me/tondev_news) Telegram channel announcement: https://t.me/tondev_news/116
- [ ] Accumulate TON dev chats feedback
