### ISSUE TITLE
Tact v1.4.0 release checklist

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact#391]
- [x] Improve the changelog for `v1.4.0`: grammar, wording, polishing:
  - [x] json-schemas -> schemas in changelog: see [this comment](https://github.com/tact-lang/tact/pull/410#pullrequestreview-2112823431)
  - [x] remove "Inferring `void` type in let statements is now forbidden" from the Fixed section
- [x] Make sure there are no open issues for the [v1.4.0 milestone](https://github.com/tact-lang/tact/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.4.0)
      (except for the current one, of course)
- [x] Bump Tact version in:
  - [x] [`package.json`](./package.json) file
  - [x] [CHANGELOG.md](./CHANGELOG.md): `Unreleased` -> `v1.4.0`
- [x] Tag the new `v1.4.0` release in Git
  ```shell
  $ git tag v1.4.0
  $ git push origin v1.4.0
  ```
- [x] Create the new `v1.4.0` release on GitHub: <https://github.com/tact-lang/tact/releases>
- [x] Publish the new `v1.4.0` release on NPM:
      [@tact-lang/compiler](https://www.npmjs.com/package/@tact-lang/compiler)
  ```shell
  $ git checkout v1.4.0
  $ yarn all && npm publish
  ```
- [x] Update [tact-docs](https://github.com/tact-lang/tact-docs) with the most recent Tact features (tracked in: https://github.com/tact-lang/tact-docs/issues/255)
- [x] Request or perform the plugins/parsers/tools updates and releases:
  - [x] <https://github.com/tact-lang/tact-template> (tracked in: https://github.com/tact-lang/tact-template/issues/22)
  - [x] <https://github.com/tact-lang/tree-sitter-tact> (tracked in: https://github.com/tact-lang/tree-sitter-tact/issues/32)
  - [x] <https://github.com/tact-lang/tact.vim> (tracked in: https://github.com/tact-lang/tact.vim/issues/32)
  - [x] <https://github.com/tact-lang/tact-vscode> (tracked in: https://github.com/tact-lang/tact-vscode/issues/36)
  - [x] <https://github.com/tact-lang/tact-sublime> (tracked in: https://github.com/tact-lang/tact-sublime/issues/14)
  - ~A new release of [tact-vscode](https://marketplace.visualstudio.com/items?itemName=KonVik.tact-lang-vscode) on the Visual Studio Marketplace~
  - [x] <https://github.com/novusnota/prism-ton> (tracked in: https://github.com/novusnota/prism-ton/issues/5)
  - [x] <https://github.com/nujan-io/nujan-ide> (tracked in: https://github.com/nujan-io/nujan-ide/issues/42)
  - [x] <https://github.com/ton-org/blueprint>
  - [x] <https://github.com/ton-blockchain/intellij-ton> (tracked in: https://github.com/ton-blockchain/intellij-ton/issues/180)
- ~Write `v1.4.0` release notes explaining the newest changes with code examples~ (pushed to 1.4.1)
- ~[TON Dev News](https://t.me/tondev_news) Telegram channel announcement~ (pushed to 1.4.1)
- ~Accumulate TON dev chats feedback~ (pushed to 1.4.1)

**Comment by novusnota** [comment]
Oh, we should also add https://github.com/tact-lang/tact-sublime to that list now :)
