### ISSUE TITLE
Tact v1.4.1 release checklist

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact#470]
- [x] Improve the changelog for `v1.4.1`: grammar, wording, polishing:
- [x] Make sure there are no open issues for the [v1.4.1 milestone](https://github.com/tact-lang/tact/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.4.1)
      (except for the current one, of course)
- [x] Bump Tact version in:
  - [x] [`package.json`](./package.json) file
  - [x] [CHANGELOG.md](./CHANGELOG.md): `Unreleased` -> `v1.4.1`
- [x] Tag the new `v1.4.1` release in Git
  ```shell
  $ git tag v1.4.1
  $ git push origin v1.4.1
  ```
- [x] Create the new `v1.4.1` release on GitHub: <https://github.com/tact-lang/tact/releases>
- [x] Publish the new `v1.4.1` release on NPM:
      [@tact-lang/compiler](https://www.npmjs.com/package/@tact-lang/compiler)
  ```shell
  $ git checkout v1.4.1
  $ yarn all && npm publish
  ```
- ~Update [tact-docs](https://github.com/tact-lang/tact-docs) with the most recent Tact features (tracked in: https://github.com/tact-lang/tact-docs/issues/255)~
- [x] Request or perform the plugins/parsers/tools updates and releases:
  - ~<https://github.com/tact-lang/tact-template> (tracked in: https://github.com/tact-lang/tact-template/issues/22)~
  - ~<https://github.com/tact-lang/tree-sitter-tact> (tracked in: https://github.com/tact-lang/tree-sitter-tact/issues/32)~
  - ~<https://github.com/tact-lang/tact.vim> (tracked in: https://github.com/tact-lang/tact.vim/issues/32)~
  - ~<https://github.com/tact-lang/tact-vscode> (tracked in: https://github.com/tact-lang/tact-vscode/issues/36)~
  - ~<https://github.com/tact-lang/tact-sublime> (tracked in: https://github.com/tact-lang/tact-sublime/issues/14)~
  - [x] A new release of [tact-vscode](https://marketplace.visualstudio.com/items?itemName=KonVik.tact-lang-vscode) on the Visual Studio Marketplace
  - ~<https://github.com/novusnota/prism-ton> (tracked in: https://github.com/novusnota/prism-ton/issues/5)~
  - [x] <https://github.com/nujan-io/nujan-ide> (tracked in: https://github.com/nujan-io/nujan-ide/issues/47)
  - ~<https://github.com/ton-org/blueprint>~
  - ~<https://github.com/ton-blockchain/intellij-ton> (tracked in: https://github.com/ton-blockchain/intellij-ton/issues/180)~
- ~Write `v1.4.1` release notes explaining the newest changes with code examples~
- ~[TON Dev News](https://t.me/tondev_news) Telegram channel announcement~
- ~Accumulate TON dev chats feedback~
