### ISSUE TITLE
Tact v1.4.2 release checklist

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact#684]
- [x] Improve the changelog for `v1.4.2`: grammar, wording, polishing
- [x] Make sure there are no open issues for the [v1.4.2 milestone](https://github.com/tact-lang/tact/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.4.2) (except for the current one, of course)
- [x] Bump Tact version in:
  - [x] [`package.json`](./package.json) file
  - [x] [CHANGELOG.md](./CHANGELOG.md): `Unreleased` -> `v1.4.2`
- [x] Tag the new `v1.4.2` release in Git
  ```shell
  $ git tag v1.4.2
  $ git push origin v1.4.2
  ```
- [x] Create the new `v1.4.2` release on GitHub: <https://github.com/tact-lang/tact/releases>
- [x] Publish the new `v1.4.2` release on NPM: [@tact-lang/compiler](https://www.npmjs.com/package/@tact-lang/compiler)
  ```shell
  $ git checkout v1.4.2
  $ yarn all && npm publish
  ```
- Request or perform the plugins/parsers/tools updates and releases:
  - [x] <https://github.com/tact-lang/tact-template> (tracked in: https://github.com/tact-lang/tact-template/issues/25)
  - ~[ ] <https://github.com/tact-lang/tact-vscode> (tracked in: https://github.com/tact-lang/tact-vscode/issues/42)~
  - ~[ ] A new release of [tact-vscode](https://marketplace.visualstudio.com/items?itemName=KonVik.tact-lang-vscode) on the Visual Studio Marketplace~
  - ~[ ] <https://github.com/nujan-io/nujan-ide> (tracked in: https://github.com/nujan-io/nujan-ide/issues/78)~
- ~[ ] [TON Dev News](https://t.me/tondev_news) Telegram channel announcement~
- ~[ ] Accumulate TON dev chats feedback~
