### ISSUE TITLE
Tact v1.5.0 release checklist

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact#832]
- [x] Improve the changelog for `v1.5.0`: grammar, wording, polishing
- [x] Make sure there are no open issues for the [v1.5.0 milestone](https://github.com/tact-lang/tact/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.5.0) (except for the current one, of course)
- [x] Bump Tact version in:
  - [x] [`package.json`](./package.json) file
  - [x] [CHANGELOG.md](./CHANGELOG.md): `Unreleased` -> `v1.5.0`
- [x] Tag the new `v1.5.0` release in Git
  ```shell
  $ git tag v1.5.0
  $ git push origin v1.5.0
  ```
- [x] Create the new `v1.5.0` release on GitHub: <https://github.com/tact-lang/tact/releases>
- [x] Publish the new `v1.5.0` release on NPM: [@tact-lang/compiler](https://www.npmjs.com/package/@tact-lang/compiler)
  ```shell
  $ git checkout v1.5.0
  $ yarn all && npm publish
  ```
- [x] Update [tact-docs](https://github.com/tact-lang/tact-docs) with the most recent Tact features (tracked in: https://github.com/tact-lang/tact-docs/milestone/6)
- [x] Request or perform the plugins/parsers/tools updates and releases:
  - [x] <https://github.com/tact-lang/tact-template> (tracked in: https://github.com/tact-lang/tact-template/issues/31)
  - [x] <https://github.com/tact-lang/tree-sitter-tact> (tracked in: https://github.com/tact-lang/tree-sitter-tact/issues/39)
  - [x] <https://github.com/tact-lang/tact.vim> (tracked in: https://github.com/tact-lang/tact.vim/issues/35)
  - [x] <https://github.com/tact-lang/tact-sublime> (tracked in: https://github.com/tact-lang/tact-sublime/issues/22)
  - [x] <https://github.com/tact-lang/tact-vscode> (tracked in: https://github.com/tact-lang/tact-vscode/issues/44)
  - [x] A new release of [tact-vscode](https://marketplace.visualstudio.com/items?itemName=KonVik.tact-lang-vscode) on the Visual Studio Marketplace
  - [x] <https://github.com/novusnota/prism-ton> (tracked in: https://github.com/novusnota/prism-ton/issues/7)
  - [x] <https://github.com/nujan-io/nujan-ide> (tracked in: https://github.com/nujan-io/nujan-ide/issues/104)
  - [ ] <https://github.com/ton-blockchain/intellij-ton> (tracked in: https://github.com/ton-blockchain/intellij-ton/issues/193)
- [x] [TON Dev News](https://t.me/tondev_news) Telegram channel announcement
- [x] Accumulate TON dev chats feedback

**Comment by novusnota** [comment]
With https://github.com/tact-lang/tact/pull/1061 merged, we've finally covered the docs for 1.5.0 :rocket:
See the changelog: https://github.com/tact-lang/tact/blob/main/CHANGELOG.md#150---2024-09-15

As for the Tact 1.6.0, docs are being written as new PRs come out, so there's no lagging behind anymore.
