### ISSUE TITLE
Tact v1.5.1 release checklist

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact#849]
- [x] Improve the changelog for `v1.5.1`: grammar, wording, polishing
- [x] Make sure there are no open issues for the [v1.5.1 milestone](https://github.com/tact-lang/tact/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.5.1) (except for the current one, of course)
- [x] Bump Tact version in:
  - [x] [`package.json`](./package.json) file
  - [x] [CHANGELOG.md](./CHANGELOG.md): `Unreleased` -> `v1.5.1`
- [x] Tag the new `v1.5.1` release in Git
  ```shell
  $ git tag v1.5.1
  $ git push origin v1.5.1
  ```
- [x] Create the new `v1.5.1` release on GitHub: <https://github.com/tact-lang/tact/releases>
- [x] Publish the new `v1.5.1` release on NPM: [@tact-lang/compiler](https://www.npmjs.com/package/@tact-lang/compiler)
  ```shell
  $ git checkout v1.5.1
  $ yarn all && npm publish
  ```
